apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: ''
  volumeName: day55-pv
