apiVersion: v1
kind: Pod
metadata:
  name: team-pod
  labels:
    app: nginx
    environment: staging
    team: platform
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
