{
 "title": "DevOps Observability Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Usage %",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "100 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "gauge",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "(1-node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes)*100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container CPU",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name!=\"\"}[5m])*100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Memory MiB",
   "type": "barchart",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name!=\"\"}/1024/1024",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "stat",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "(1-node_filesystem_avail_bytes{mountpoint=\"/\"}/node_filesystem_size_bytes{mountpoint=\"/\"})*100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "x": 0, "y": 40, "w": 24, "h": 10 },
   "targets": [
    {
     "expr": "{container_name=\"notes-app\"}"
    }
   ]
  }
 ]
}