services:
  web:
    image: nginx:alpine
    #container_name: day19-web
    ports:
      #- "8081:80"
      - "80"
    networks:
      - day19-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: day19-db
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: "devopsdb"
      MYSQL_USER: "devops"
      MYSQL_PASSWORD: "devopspassword"
    ports:
      - "3306:3306"
    volumes:
      - day19-db-data:/var/lib/mysql
    networks:
      - day19-network

volumes:
  day19-db-data:

networks:
  day19-network:
    driver: bridge
